spring:

  flyway:
    enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:scartdb
    username: sa
    password:
    driverClassName: org.h2.Driver